export const CHECKLIST_DATA = {
  checklists: [
    {
      id: "65f2b3db5a5ecabbbcc6db90",
      name: "Plan",
      idBoard: "65f2b3d95a5ecabbbcc6bb0f",
      idCard: "65f2b3db5a5ecabbbcc6d961",
      pos: 16384,
      limits: {
        checkItems: {
          perChecklist: {
            status: "ok",
            disableAt: 200,
            warnAt: 160,
          },
        },
      },
      checkItems: [
        {
          id: "65f2b3ff5a5ecabbbcc78a0a",
          name: "Add routing for plan and followup",
          nameData: {
            emoji: {},
          },
          pos: 16736,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a0b",
          name: "Add argomento GRAZ in all enums and translations",
          nameData: {
            emoji: {},
          },
          pos: 33633,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a0c",
          name: "Add doctor data component & logic",
          nameData: {
            emoji: {},
          },
          pos: 50275,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a0d",
          name: "Add documentation link",
          nameData: {
            emoji: {},
          },
          pos: 41954,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a0e",
          name: "Add assistito component & logic",
          nameData: {
            emoji: {},
          },
          pos: 67527,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a0f",
          name: "Create GRAZ type",
          nameData: {
            emoji: {},
          },
          pos: 84118,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a10",
          name: "Add drug in dataset",
          nameData: {
            emoji: {},
          },
          pos: 143162,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a11",
          name: "Add dates",
          nameData: {
            emoji: {},
          },
          pos: 185647,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a12",
          name: "Add buttons",
          nameData: {
            emoji: {},
          },
          pos: 202875,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a13",
          name: "Save draft and check all send values",
          nameData: {
            emoji: {},
          },
          pos: 219678,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a14",
          name: "Open saved draft from search with cf, name & surname, only drafts and check values",
          nameData: {
            emoji: {},
          },
          pos: 236445,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a15",
          name: "Send plan & check all values, pdf, values in tab piano attivo",
          nameData: {
            emoji: {},
          },
          pos: 253073,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a16",
          name: "Cancel plan with new plan",
          nameData: {
            emoji: {},
          },
          pos: 269625,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a17",
          name: "Cancel plan with X button",
          nameData: {
            emoji: {},
          },
          pos: 286388,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a18",
          name: "Hide save draft button",
          nameData: {
            emoji: {},
          },
          pos: 261349,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a19",
          name: "Add plan config",
          nameData: {
            emoji: {},
          },
          pos: 37793.5,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a1a",
          name: "Add `nome commerciale del farmaco prescritto` disabeld dropdown",
          nameData: {
            emoji: {},
          },
          pos: 147389,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a1b",
          name: "Add title and sub title for forst plan",
          nameData: {
            emoji: {},
          },
          pos: 39873.75,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a1c",
          name: "Add labels",
          nameData: {
            emoji: {},
          },
          pos: 100771,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a1d",
          name: "Test sorting & filtering in home table",
          nameData: {
            emoji: {},
          },
          pos: 303269,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a1e",
          name: "Add principio attivo",
          nameData: {
            emoji: {},
          },
          pos: 145275.5,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a1f",
          name: "Add dose",
          nameData: {
            emoji: {},
          },
          pos: 148445.75,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a20",
          name: "Add diagnosi checkboxes",
          nameData: {
            emoji: {},
          },
          pos: 111368.75,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a21",
          name: "Add information notes & translations",
          nameData: {
            emoji: {},
          },
          pos: 116667.625,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a22",
          name: "Add therapy section",
          nameData: {
            emoji: {},
          },
          pos: 129914.8125,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db90",
        },
      ],
      creationMethod: null,
    },
    {
      id: "65f2b3db5a5ecabbbcc6db91",
      name: "Followup",
      idBoard: "65f2b3d95a5ecabbbcc6bb0f",
      idCard: "65f2b3db5a5ecabbbcc6d961",
      pos: 32768,
      limits: {
        checkItems: {
          perChecklist: {
            status: "ok",
            disableAt: 200,
            warnAt: 160,
          },
        },
      },
      checkItems: [
        {
          id: "65f2b3fa5a5ecabbbcc76f00",
          name: "Create followup component page",
          nameData: {
            emoji: {},
          },
          pos: 16945,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3fa5a5ecabbbcc76f01",
          name: "Add routing",
          nameData: {
            emoji: {},
          },
          pos: 33334,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3fa5a5ecabbbcc76f02",
          name: "Open first followup from plan & check values in pianoAttivo tab",
          nameData: {
            emoji: {},
          },
          pos: 50245,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3fa5a5ecabbbcc76f03",
          name: "Save first followup draft from plan & check sending correct values + open the draft & check loading correct values",
          nameData: {
            emoji: {},
          },
          pos: 66926,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3fa5a5ecabbbcc76f04",
          name: "Send first followup from plan -\u003E check values",
          nameData: {
            emoji: {},
          },
          pos: 83556,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3fa5a5ecabbbcc76f05",
          name: "Open a followup from followup & check values in pianoAttivo tab",
          nameData: {
            emoji: {},
          },
          pos: 100763,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3fa5a5ecabbbcc76f06",
          name: "Save followup from followup draft & check sending correct values + open the draft & check loading correct values",
          nameData: {
            emoji: {},
          },
          pos: 117424,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3fa5a5ecabbbcc76f07",
          name: "Send followup from followup -\u003E check values",
          nameData: {
            emoji: {},
          },
          pos: 134473,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a3e",
          name: "Add ngIf followup logic",
          nameData: {
            emoji: {},
          },
          pos: 41789.5,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a3f",
          name: "Add radio buttons and input (like NINU)",
          nameData: {
            emoji: {},
          },
          pos: 46017.25,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a40",
          name: "Add section SEVERITA and checkboxes",
          nameData: {
            emoji: {},
          },
          pos: 48131.125,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a41",
          name: "Add section DURATA and checkboxes",
          nameData: {
            emoji: {},
          },
          pos: 49188.0625,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a42",
          name: "Add FEV1 radio buttons",
          nameData: {
            emoji: {},
          },
          pos: 49716.53125,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a43",
          name: "Add terapia component",
          nameData: {
            emoji: {},
          },
          pos: 49980.765625,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a44",
          name: "Add radiobuttons ricoveri",
          nameData: {
            emoji: {},
          },
          pos: 50112.8828125,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a45",
          name: "Add comorbidity checkboxes & input field",
          nameData: {
            emoji: {},
          },
          pos: 49452.296875,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a46",
          name: "Add principio attivo, nome farmaco & dose dropdowns ",
          nameData: {
            emoji: {},
          },
          pos: 50178.94140625,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a47",
          name: "Check value  hospitalizations is correctly saved and retrieved in draft ",
          nameData: {
            emoji: {},
          },
          pos: 87857.75,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a48",
          name: "Check Il paziente ha effettuato il trattamento con GRAZAX? - no value in draft followup",
          nameData: {
            emoji: {},
          },
          pos: 85706.875,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a49",
          name: "Remove * & bold  from number of hospitalizations when not required ",
          nameData: {
            emoji: {},
          },
          pos: 96461.25,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a4a",
          name: "Remove error undefined hospitalizations in followup ",
          nameData: {
            emoji: {},
          },
          pos: 86782.3125,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
        {
          id: "65f2b3ff5a5ecabbbcc78a4b",
          name: "Reset value hospitalizations when No is selected ",
          nameData: {
            emoji: {},
          },
          pos: 92159.5,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db91",
        },
      ],
      creationMethod: null,
    },
    {
      id: "65f2b3db5a5ecabbbcc6db92",
      name: "Monitoraggio",
      idBoard: "65f2b3d95a5ecabbbcc6bb0f",
      idCard: "65f2b3db5a5ecabbbcc6d961",
      pos: 49152,
      limits: {
        checkItems: {
          perChecklist: {
            status: "ok",
            disableAt: 200,
            warnAt: 160,
          },
        },
      },
      checkItems: [
        {
          id: "65f2b3fb5a5ecabbbcc77586",
          name: "Add doctor role",
          nameData: {
            emoji: {},
          },
          pos: 17283,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db92",
        },
        {
          id: "65f2b3fb5a5ecabbbcc77587",
          name: "Search & filter by GRAZ -\u003E check if the filter works as expected with the new argomento",
          nameData: {
            emoji: {},
          },
          pos: 150606,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db92",
        },
        {
          id: "65f2b3fb5a5ecabbbcc77588",
          name: "Visualiza",
          nameData: {
            emoji: {},
          },
          pos: 51681,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db92",
        },
        {
          id: "65f2b3fb5a5ecabbbcc77589",
          name: "Principio Attivo",
          nameData: {
            emoji: {},
          },
          pos: 68117,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db92",
        },
        {
          id: "65f2b3fb5a5ecabbbcc7758a",
          name: "Diagnosi ",
          nameData: {
            emoji: {},
          },
          pos: 85070,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db92",
        },
        {
          id: "65f2b3fb5a5ecabbbcc7758b",
          name: "Add plan to monitoraggio visualizza component",
          nameData: {
            emoji: {},
          },
          pos: 34482,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db92",
        },
        {
          id: "65f2b3fb5a5ecabbbcc7758c",
          name: "Export table and check values",
          nameData: {
            emoji: {},
          },
          pos: 265852,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db92",
        },
        {
          id: "65f2b3fb5a5ecabbbcc7758d",
          name: "Test new role",
          nameData: {
            emoji: {},
          },
          pos: 25882.5,
          state: "complete",
          due: null,
          dueReminder: null,
          idMember: "65f2b3d95a5ecabbbcc6bb3c",
          idChecklist: "65f2b3db5a5ecabbbcc6db92",
        },
      ],
      creationMethod: null,
    },
  ],
};
